### ISSUE TITLE
set max_avg_val to negative infinity

### ISSUE THREAD

**Issue by ad3429** [SergioCantera/pwp-capstones#2]
https://github.com/SergioCantera/pwp-capstones/blob/master/TomeRater/TomeRater.py#L202

Instead of setting the max_avg_val to 0, it is better practice to initialize it to some impossible value such as negative infinity:

`highest_avg_val = float("-inf")`

**Comment by SergioCantera** [comment]
Thank you very much for this valuable advice!!! From now on I will keep it in mind for future projects.
