### ISSUE TITLE
SUMMARY - Tome Rater Project

### ISSUE THREAD

**Issue by ad3429** [SergioCantera/pwp-capstones#3]
**Criteria 1: Valid Python Code**

Score Level: 4/4

**Criteria 2: Implementation of Project Requirements**

Score Level: 4/4

Comment(s): Nice job implementing the requirements of the project, and also paying close attention to details such as checking for invalid values.

**Criteria 3: Software Architecture**

Score Level: 4/4

Comment(s): Nice job separating your code in different classes and functions, and keeping it very organized! One thing to look out for is when you set the max_value or max_average_value you want to set it equal to some impossible value such as negative infinity, rather than initializing it to a value such as 0. 

**Criteria 4: Uses Python Language Features**

Score Level: 4/4

Comment(s): Great use of python language features.

Overall Score: 16/16

Overall great job! I have made some comments about your code in the "Issues" section above. Most of the issues are quite minor and just suggestions on how to further improve your python code. You successfully implemented all of the requirements of the project, and It's very clear that your python skills have been improving. Make sure to keep up the good work!

**Comment by SergioCantera** [comment]
Thank you very much for your review and the evaluation you've done about my project. I'm really happy for completing this course.
Now, I'm going to practice the Python skills I've obtained and trying to improve day by day.
